<a href="https://colab.research.google.com/github/w2k31984/Numpy_DS/blob/master/numpy_DS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Trabajando con Numpy para ciencia de datos.

In [1]:
#Importamos la libreria de numpy a nuestro proyecto
import numpy as np
#pip install numpy


In [2]:
#Ejemplos de Arrays en Python
array_1d=np.array([1,4,3])
array_1d


array([1, 4, 3])

In [3]:
array_2d=np.array([(1,5,7),(3,7,1)])
array_2d

array([[1, 5, 7],
       [3, 7, 1]])

In [5]:
array_3d=np.array([[(1,4,2),(3,7,9)],[(4,0,8),(2,5,1)],[(3,9,2),(1,7,5)]],dtype=float)
array_3d

array([[[1., 4., 2.],
        [3., 7., 9.]],

       [[4., 0., 8.],
        [2., 5., 1.]],

       [[3., 9., 2.],
        [1., 7., 5.]]])

Creando Arrays

In [9]:
#De ceros con tres filas y cuatro columnas
array_Ceros=np.zeros((3,4))
array_Ceros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
print(np.zeros((4,5)))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [11]:
#Array de 2 dimensiones 4 filas 5 columnas
array_2d_4f_5c=np.ones((2,4,5))
array_2d_4f_5c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [13]:
#Array de intervalos y saltos
array_inter_saltos=np.arange(12,31,2)
array_inter_saltos

array([12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [14]:
#Array de Intervalos y divisiones
array_inter_div=np.linspace(0,4,7)
array_inter_div

array([0.        , 0.66666667, 1.33333333, 2.        , 2.66666667,
       3.33333333, 4.        ])

In [16]:
#Valor dado
array_valor_dado=np.full((3,3),8)
array_valor_dado

array([[8, 8, 8],
       [8, 8, 8],
       [8, 8, 8]])

In [18]:
#Array matriz identidad diagonal de unos
array_matriz_identidad=np.eye(3)
array_matriz_identidad

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])