<a href="https://colab.research.google.com/github/w2k31984/Numpy_DS/blob/master/numpy_DS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Trabajando con Numpy para ciencia de datos.

In [1]:
#Importamos la libreria de numpy a nuestro proyecto
import numpy as np
#pip install numpy


In [2]:
#Ejemplos de Arrays en Python
array_1d=np.array([1,4,3])
array_1d


array([1, 4, 3])

In [3]:
array_2d=np.array([(1,5,7),(3,7,1)])
array_2d

array([[1, 5, 7],
       [3, 7, 1]])

In [5]:
array_3d=np.array([[(1,4,2),(3,7,9)],[(4,0,8),(2,5,1)],[(3,9,2),(1,7,5)]],dtype=float)
array_3d

array([[[1., 4., 2.],
        [3., 7., 9.]],

       [[4., 0., 8.],
        [2., 5., 1.]],

       [[3., 9., 2.],
        [1., 7., 5.]]])

Creando Arrays

In [9]:
#De ceros con tres filas y cuatro columnas
array_Ceros=np.zeros((3,4))
array_Ceros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
print(np.zeros((4,5)))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [11]:
#Array de 2 dimensiones 4 filas 5 columnas
array_2d_4f_5c=np.ones((2,4,5))
array_2d_4f_5c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [13]:
#Array de intervalos y saltos
array_inter_saltos=np.arange(12,31,2)
array_inter_saltos

array([12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [14]:
#Array de Intervalos y divisiones
array_inter_div=np.linspace(0,4,7)
array_inter_div

array([0.        , 0.66666667, 1.33333333, 2.        , 2.66666667,
       3.33333333, 4.        ])

In [16]:
#Valor dado
array_valor_dado=np.full((3,3),8)
array_valor_dado

array([[8, 8, 8],
       [8, 8, 8],
       [8, 8, 8]])

In [18]:
#Array matriz identidad diagonal de unos
array_matriz_identidad=np.eye(3)
array_matriz_identidad

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
#Array de Valores aleatorios entre 0 y 1
array_val_aleatorios=np.random.random((4,4))
array_val_aleatorios

array([[0.10261195, 0.50036889, 0.1946128 , 0.16939389],
       [0.42916305, 0.35005278, 0.95497887, 0.75235134],
       [0.08648701, 0.37174275, 0.05627783, 0.09460181],
       [0.83368026, 0.28036865, 0.00606296, 0.42938802]])

In [20]:
#Array vacio de 4 filas y 3 columnas
array_vacio=np.empty((4,3))
array_vacio

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Escritura y lectura de arrays sobre textos

In [21]:
#Grabar Arrays
np.save('my_array',np.random.random((3,3)))


In [22]:
#Cargar Arrays
my_array_carga=np.load('my_array.npy')
my_array_carga


array([[0.0550751 , 0.62643759, 0.58375114],
       [0.88924364, 0.36585138, 0.46895533],
       [0.29067814, 0.32833717, 0.46607802]])