<a href="https://colab.research.google.com/github/w2k31984/Numpy_DS/blob/master/numpy_DS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Trabajando con Numpy para ciencia de datos.

In [1]:
#Importamos la libreria de numpy a nuestro proyecto
import numpy as np
#pip install numpy


In [2]:
#Ejemplos de Arrays en Python
array_1d=np.array([1,4,3])
array_1d


array([1, 4, 3])

In [3]:
array_2d=np.array([(1,5,7),(3,7,1)])
array_2d

array([[1, 5, 7],
       [3, 7, 1]])

In [4]:
array_3d=np.array([[(1,4,2),(3,7,9)],[(4,0,8),(2,5,1)],[(3,9,2),(1,7,5)]])
array_3d

array([[[1, 4, 2],
        [3, 7, 9]],

       [[4, 0, 8],
        [2, 5, 1]],

       [[3, 9, 2],
        [1, 7, 5]]])